sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"
  - "8.4.0"

addons:
  sauce_connect: true

script:
  - docker-compose ps
  - docker-compose down
  - docker-compose up --build -d
  - npm run lint && npm run type-check && npm run e2e
