sudo: required

services:
  - docker

language: node_js
node_js:
  - "8.4.0"

addons:
  sauce_connect: true

before_script:
  - docker-compose up --build -d
  - sleep 30

script:
  # - npm test
  # - npm run lint
  # - npm run type-check
  - docker-compose ps
  - curl http://localhost:8080
  - npm run e2e
