sudo: required

services:
  - docker

language: node_js
node_js:
  - "8.4.0"

before_script:
  - docker-compose up --build &
  - sleep 60
  - docker-compose ps

script:
  - npm run i-all
  - npm test
  - npm run lint
  - npm run type-check
  - npm run e2e
