sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"
  - "8.4.0"

addons:
  sauce_connect: true

before_script:
  - docker-compose up --build -d

script:
  - npm test
  - npm run lint
  - npm run type-check
  - npm run e2e
