sudo: required

language: node_js
node_js:
  - "8.4.0"

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - npm run i-all
  - npm test
  - npm run lint
  - npm run type-check
  # - npm run e2e
  - docker build -t $DOCKER_USERNAME/engage_client ./client
  - docker push $DOCKER_USERNAME/engage_client
  - docker build -t $DOCKER_USERNAME/engage_jwt ./jwt
  - docker push $DOCKER_USERNAME/engage_jwt
  - docker build -t $DOCKER_USERNAME/engage_server ./server
  - docker push $DOCKER_USERNAME/engage_server
  - curl "http://engage.smith-stevens.com:8089/update"
# - docker-machine create --driver digitalocean --digitalocean-image ubuntu-16-04-x64 --digitalocean-access-token $DO_TOKEN engage-machine
# - docker-machine scp -r /Users/hally9k/Repos/Engage/docker-stack.yml engage-machine:/home/engage/docker-stack.yml
# - docker-machine scp -r /Users/hally9k/Repos/Engage/server/database/ engage-machine:/home/engage/server/
# docker-machine ssh engage-machine
# cd /home/engage
# docker stack deploy --compose-file docker-stack.yml engage-stack
