sudo: required

language: node_js
node_js:
  - "8.4.0"

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - npm run i-all
  - npm test
  - npm run lint
  - npm run type-check
  - npm run e2e
  - docker build -t $DOCKER_USERNAME/engage_client ./client
  - docker push $DOCKER_USERNAME/engage_client
  - docker build -t $DOCKER_USERNAME/engage_jwt ./jwt
  - docker push $DOCKER_USERNAME/engage_jwt
  - docker build -t $DOCKER_USERNAME/engage_server ./server
  - docker push $DOCKER_USERNAME/engage_server
  # - docker-machine create --driver digitalocean --digitalocean-image ubuntu-16-04-x64 --digitalocean-access-token $DOTOKEN engage
  # - docker stack deploy -c ./docker-stack.yml engage-stack
