version: "2"
services:
  db:
    image: postgres
    volumes:
      - ./config/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
