version: "3"
services:
  jwt:
    build: ./jwt
    ports:
      - "8082:8082"
    environment:
      - PG_HOST=db
  db:
    image: postgres
    volumes:
      - ./server/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
  server:
    build: ./server
    volumes:
      - "./server:/usr/src/engage"
    ports:
      - "8081:8081"
    depends_on:
      - "redis"
      - "db"
    restart: unless-stopped
  client:
    build: ./client
    volumes:
      - "./client:/usr/src/engage"
    ports:
      - "8080:8080"
