version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080"
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5444"
  redis:
    image: redis
    ports:
     - "6379"
