version: "3"
services:
  jwt:
    build: ./jwt
    ports:
      - "8082:8082"
      - "9202:9202"
    environment:
      - PG_HOST=db
    command: node -r @std/esm --inspect=0.0.0.0:9202 index.js
  image-upload:
    build: ./image-upload
    ports:
      - "8083:8083"
      - "9203:9203"
    environment:
      - PG_HOST=db
    command: ./node_modules/.bin/babel-node --inspect=0.0.0.0:9203 index.js
  db:
    image: postgres
    volumes:
      - ./server/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379"
  server:
    build: ./server
    volumes:
      - "./server:/usr/src/engage"
    ports:
      - "8081:8081"
      - "9201:9201"
    depends_on:
      - "redis"
      - "db"
    restart: unless-stopped
    command: ./node_modules/.bin/babel-node --inspect=0.0.0.0:9201 index.js
  # client:
  #   build: ./client
  #   ports:
  #     - "8080:8080"
