  version: "2"
  services:
    db:
      image: postgres
      ports:
        - "5432"
    redis:
      image: redis
      ports:
        - "6379"
    web:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - "redis"
        - "db"
      restart: unless-stopped
